local names = {
	"Brother Athelstan",
	"Brother Hogo",
	"Brother Godwin",
	"Brother Alfred",
	"Brother Gilbert",
	"Brother Francis",
	"Brother Michael",
	"Brother Ecbert",
	"Brother Edmund",
	"Brother Wilfred",
	"Brother Godfrey",
	"Brother Benedict",
	"Brother Thomas",
	"Brother Bernard",
	"Brother Stephen",
	"Brother Alberic",
	"Brother Peter",
	"Brother Kasimir",
	"Brother Augustus",
	"Brother John",
	"Brother Thomas",
	"Brother Godel",
	"Brother David",
	"Brother Timothy",
	"Brother Francis",
	"Brother Nicodemus",
	"Brother Abel",
	"Brother Cain",
}

return names
